version: '3.8'
services:
  web:
    build: .
    command: gunicorn main:app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://root:YtrSWVDVQUAZzqbCwngpdhZFakJtVpvo@junction.proxy.rlwy.net:19122/railway
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YtrSWVDVQUAZzqbCwngpdhZFakJtVpvo
      MYSQL_DATABASE: railway
    ports:
      - "19122:19122"

