version: '3.8'
services:
  web:
    build: .
    command: gunicorn main:app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://root:mysql1234@db:3306/escola
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql1234
      MYSQL_DATABASE: escola
    ports:
      - "3306:3306"

